services:
  redis:
    image: redis:alpine
    container_name: imagebot-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    env_file:
      - .env
  bot:
    build: .
    container_name: orimi-bot
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "8001:8001"