version: '3.9'

services:
  redis:
    image: redis:alpine
    container_name: orimi-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env


  bot:
    build: .
    container_name: orimi-bot
    depends_on:
      - redis
    env_file:
      - .env